/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AboutImport } from './routes/about'
import { Route as AuthenticatedIndexImport } from './routes/_authenticated/index'
import { Route as AuthenticatedCreateBlogImport } from './routes/_authenticated/create-blog'
import { Route as AuthenticatedAllBlogsImport } from './routes/_authenticated/all-blogs'

// Create/Update Routes

const AboutRoute = AboutImport.update({
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedIndexRoute = AuthenticatedIndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedCreateBlogRoute = AuthenticatedCreateBlogImport.update({
  path: '/create-blog',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedAllBlogsRoute = AuthenticatedAllBlogsImport.update({
  path: '/all-blogs',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/all-blogs': {
      preLoaderRoute: typeof AuthenticatedAllBlogsImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/create-blog': {
      preLoaderRoute: typeof AuthenticatedCreateBlogImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/': {
      preLoaderRoute: typeof AuthenticatedIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  AboutRoute,
  AuthenticatedAllBlogsRoute,
  AuthenticatedCreateBlogRoute,
  AuthenticatedIndexRoute,
])

/* prettier-ignore-end */
